name: Map Deployment

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [data_release] # this is a trigger used by the mapping-data repository

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Build map
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 24h
          script: |
            #!/usr/bin/env bash
            set -e
            cd /pf-mapping
            git pull
            docker stop pf-map-compiler || true
            docker build -t pf-wikis/mapping -f build/Dockerfile .
            docker run --name pf-map-compiler --rm -v /wikis/volumes/map:/w/output pf-wikis/mapping
            docker restart page_cache
            docker container prune -f
