name: Tile Compiler Deploy

on:
  workflow_call:
  push:
    branch: 'main'
    paths:
      - 'tile-compiler/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: tile-compiler
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build
        run: |
          cd tile-compiler
          mvn -B package
      - name: Delete old package
        uses: actions/delete-package-versions@v4
        continue-on-error: true
        with:
          package-name: io.github.pf-wikis.tile-compiler
          package-type: maven
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 0
      - name: Deploy
        run: |
          cd tile-compiler
          mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
